























.build/atmega328-d1ebc9f8/SoftPWM/SoftPWM.o : lib/SoftPWM/SoftPWM.cpp
	@echo SoftPWM/SoftPWM.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/SoftPWM
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c lib/SoftPWM/SoftPWM.cpp
include .build/atmega328-d1ebc9f8/SoftPWM/SoftPWM.d



.build/atmega328-d1ebc9f8/SoftPWM/libSoftPWM.a : .build/atmega328-d1ebc9f8/SoftPWM/SoftPWM.o
	@echo Linking libSoftPWM.a
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/atmega328-d1ebc9f8/arduino/WInterrupts.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c
	@echo arduino/WInterrupts.c
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WInterrupts.c
include .build/atmega328-d1ebc9f8/arduino/WInterrupts.d

.build/atmega328-d1ebc9f8/arduino/wiring.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring.c
	@echo arduino/wiring.c
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring.c
include .build/atmega328-d1ebc9f8/arduino/wiring.d

.build/atmega328-d1ebc9f8/arduino/wiring_analog.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_analog.c
	@echo arduino/wiring_analog.c
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_analog.c
include .build/atmega328-d1ebc9f8/arduino/wiring_analog.d

.build/atmega328-d1ebc9f8/arduino/wiring_digital.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_digital.c
	@echo arduino/wiring_digital.c
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_digital.c
include .build/atmega328-d1ebc9f8/arduino/wiring_digital.d

.build/atmega328-d1ebc9f8/arduino/wiring_pulse.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c
	@echo arduino/wiring_pulse.c
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_pulse.c
include .build/atmega328-d1ebc9f8/arduino/wiring_pulse.d

.build/atmega328-d1ebc9f8/arduino/wiring_shift.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_shift.c
	@echo arduino/wiring_shift.c
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/wiring_shift.c
include .build/atmega328-d1ebc9f8/arduino/wiring_shift.d






.build/atmega328-d1ebc9f8/arduino/CDC.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/CDC.cpp
	@echo arduino/CDC.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/CDC.cpp
include .build/atmega328-d1ebc9f8/arduino/CDC.d

.build/atmega328-d1ebc9f8/arduino/HardwareSerial.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HardwareSerial.cpp
	@echo arduino/HardwareSerial.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HardwareSerial.cpp
include .build/atmega328-d1ebc9f8/arduino/HardwareSerial.d

.build/atmega328-d1ebc9f8/arduino/HID.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HID.cpp
	@echo arduino/HID.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/HID.cpp
include .build/atmega328-d1ebc9f8/arduino/HID.d

.build/atmega328-d1ebc9f8/arduino/IPAddress.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/IPAddress.cpp
	@echo arduino/IPAddress.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/IPAddress.cpp
include .build/atmega328-d1ebc9f8/arduino/IPAddress.d

.build/atmega328-d1ebc9f8/arduino/main.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp
	@echo arduino/main.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/main.cpp
include .build/atmega328-d1ebc9f8/arduino/main.d

.build/atmega328-d1ebc9f8/arduino/new.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp
	@echo arduino/new.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/new.cpp
include .build/atmega328-d1ebc9f8/arduino/new.d

.build/atmega328-d1ebc9f8/arduino/Print.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.cpp
	@echo arduino/Print.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Print.cpp
include .build/atmega328-d1ebc9f8/arduino/Print.d

.build/atmega328-d1ebc9f8/arduino/Stream.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Stream.cpp
	@echo arduino/Stream.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Stream.cpp
include .build/atmega328-d1ebc9f8/arduino/Stream.d

.build/atmega328-d1ebc9f8/arduino/Tone.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Tone.cpp
	@echo arduino/Tone.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/Tone.cpp
include .build/atmega328-d1ebc9f8/arduino/Tone.d

.build/atmega328-d1ebc9f8/arduino/USBCore.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/USBCore.cpp
	@echo arduino/USBCore.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/USBCore.cpp
include .build/atmega328-d1ebc9f8/arduino/USBCore.d

.build/atmega328-d1ebc9f8/arduino/WMath.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WMath.cpp
	@echo arduino/WMath.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WMath.cpp
include .build/atmega328-d1ebc9f8/arduino/WMath.d

.build/atmega328-d1ebc9f8/arduino/WString.o : /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.cpp
	@echo arduino/WString.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/arduino
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions  -o $@ -c /Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino/WString.cpp
include .build/atmega328-d1ebc9f8/arduino/WString.d



.build/atmega328-d1ebc9f8/arduino/libarduino.a : .build/atmega328-d1ebc9f8/arduino/WInterrupts.o .build/atmega328-d1ebc9f8/arduino/wiring.o .build/atmega328-d1ebc9f8/arduino/wiring_analog.o .build/atmega328-d1ebc9f8/arduino/wiring_digital.o .build/atmega328-d1ebc9f8/arduino/wiring_pulse.o .build/atmega328-d1ebc9f8/arduino/wiring_shift.o .build/atmega328-d1ebc9f8/arduino/CDC.o .build/atmega328-d1ebc9f8/arduino/HardwareSerial.o .build/atmega328-d1ebc9f8/arduino/HID.o .build/atmega328-d1ebc9f8/arduino/IPAddress.o .build/atmega328-d1ebc9f8/arduino/main.o .build/atmega328-d1ebc9f8/arduino/new.o .build/atmega328-d1ebc9f8/arduino/Print.o .build/atmega328-d1ebc9f8/arduino/Stream.o .build/atmega328-d1ebc9f8/arduino/Tone.o .build/atmega328-d1ebc9f8/arduino/USBCore.o .build/atmega328-d1ebc9f8/arduino/WMath.o .build/atmega328-d1ebc9f8/arduino/WString.o
	@echo Linking libarduino.a
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/atmega328-d1ebc9f8/src/sketch.o : .build/atmega328-d1ebc9f8/src/sketch.cpp
	@echo src/sketch.cpp
	@mkdir -p .build/atmega328-d1ebc9f8/src
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-g++ -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/variants/standard -Ilib/SoftPWM -I/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/arduino/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/atmega328-d1ebc9f8/src/sketch.cpp
include .build/atmega328-d1ebc9f8/src/sketch.d







.build/atmega328-d1ebc9f8/firmware.elf : .build/atmega328-d1ebc9f8/src/sketch.o .build/atmega328-d1ebc9f8/SoftPWM/libSoftPWM.a .build/atmega328-d1ebc9f8/arduino/libarduino.a
	@echo Linking firmware.elf
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gcc -Os -Wl,--gc-sections -mmcu=atmega328p -o $@ $^ -lm


.build/atmega328-d1ebc9f8/firmware.hex : .build/atmega328-d1ebc9f8/firmware.elf
	@echo Converting to firmware.hex
	@/Applications/Arduino-1.0.1.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/atmega328-d1ebc9f8/src/dependencies.d .build/atmega328-d1ebc9f8/SoftPWM/dependencies.d .build/atmega328-d1ebc9f8/arduino/dependencies.d

all : .build/atmega328-d1ebc9f8/firmware.hex
	@true

