




.build/atmega328-d1ebc9f8/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/atmega328-d1ebc9f8/src
	@echo src/sketch.ino
	@/usr/local/bin/ino preproc -d /Applications/Arduino-1.0.1.app/Contents/Resources/Java/ -o $@ $^


all : .build/atmega328-d1ebc9f8/src/sketch.cpp
	@true

